# Generated by Django 4.1.6 on 2023-02-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_slug_product_editie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='descriere',
        ),
    ]
