# Generated by Django 4.1.6 on 2023-02-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_slug_category_descriere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriere',
        ),
    ]
