# Generated by Django 4.1.6 on 2023-02-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_descriere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edition',
            field=models.SlugField(),
        ),
    ]
