# Generated by Django 4.1.6 on 2023-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_date_remove_product_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.TextField(max_length=50),
        ),
    ]
