# Generated by Django 4.1.6 on 2023-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_slug_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='editie',
            field=models.TextField(max_length=50),
        ),
    ]
