# Generated by Django 4.1.6 on 2023-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_editie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='editie',
            field=models.IntegerField(),
        ),
    ]
