# Generated by Django 4.1.6 on 2023-02-19 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editura',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
