# Generated by Django 4.1.6 on 2023-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_editura'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Ciorna'), ('waitingapproval', 'Asteapta aprobare'), ('active', 'Activ'), ('deleted', 'Sters')], default='active', max_length=50),
        ),
    ]
