# Generated by Django 4.1.6 on 2023-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_author_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
