# Generated by Django 4.1.6 on 2023-02-20 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fisier',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
