# Generated by Django 4.1.6 on 2023-02-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_fisier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fisier',
        ),
    ]
