# Generated by Django 4.1.6 on 2023-02-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf',
        ),
    ]
