# Generated by Django 4.1.6 on 2023-02-25 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_delete_author_remove_product_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/pdfs/'),
            preserve_default=False,
        ),
    ]
