# Generated by Django 4.1.6 on 2023-02-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_product_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf',
        ),
    ]
