# Generated by Django 4.1.6 on 2023-02-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_pdf_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf',
        ),
    ]
