# Generated by Django 4.1.6 on 2023-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_product_image_alter_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='editie',
            field=models.IntegerField(max_length=10),
        ),
    ]
