# Generated by Django 4.1.6 on 2023-02-28 19:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_product_editie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limba',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='editie',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub'])]),
            preserve_default=False,
        ),
    ]
