# Generated by Django 4.1.7 on 2023-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rocomanda',
            field=models.BooleanField(default=False),
        ),
    ]
