# Generated by Django 4.1.7 on 2023-03-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_product_rocomanda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rocomanda',
            new_name='recomanda',
        ),
    ]
