# Generated by Django 4.2 on 2023-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_rename_rocomanda_product_recomanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
