# Generated by Django 4.2 on 2023-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_product_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='limba',
            field=models.CharField(max_length=20),
        ),
    ]
