# Generated by Django 4.2 on 2023-05-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_product_author_alter_product_limba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
