# Generated by Django 4.2 on 2023-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_forum_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(blank=True),
        ),
    ]
