# Generated by Django 4.2 on 2023-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_discussion_created_at_discussion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
