# Generated by Django 4.2 on 2023-05-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_discussion_created_at_alter_forum_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='date_created',
        ),
    ]
