# Generated by Django 4.2 on 2023-05-17 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0056_alter_discussion_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='title',
        ),
        migrations.RenameModel(
            old_name='Forum',
            new_name='Topic',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.AddField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.topic'),
        ),
    ]
